/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://5qcc2nqwyfey5bzjamyp43b4wy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-eiosjpotfzdv3fwtqjogufluoi",
    "aws_cognito_identity_pool_id": "us-east-1:c9e1b2a5-3d21-4082-b7a7-4ab516f36e17",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_05J5imTyo",
    "aws_user_pools_web_client_id": "3h102iidgp46q54ckiuhl8fhnf",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
